const BUILTIN_TABS=[['dashboard','Dashboard'],['screener','Screener'],['strategy','Strategy Lab'],['watchlists','Watchlists'],['compare','Compare'],['sources','Data Health']];
const ALL_COLUMNS=['ticker','sector','price','price_status','market_cap','pe','pb','ps','earnings_yield','valuation_status','valuation_basis','rsi14','roe','revenue_growth_yoy','net_income_growth_yoy','revenue_quarter_yoy','net_income_quarter_yoy','volume_ratio','sector_pe_median','sector_pb_median','pe_discount_to_sector_median','pb_discount_to_sector_median','ev_ebitda','roic','net_debt_ebitda','target_upside','quality_score'];
const DEFAULT_WATCHLISTS={Core:[],Value:[],Dividend:[],Watch:[],Oversold:[]};
const DEFAULTS={theme:'system',accent:'#2563eb',density:'compact',widgets:['health','rsi','value','presets','sources'],widgetSizes:{health:'wide',sources:'wide'},tabs:['dashboard','screener','strategy','watchlists','compare','sources'],customTabs:[],activeTab:'dashboard',verifiedOnly:true,columns:['ticker','sector','price','price_status','market_cap','pe','pb','ps','roe','rsi14'],columnWidths:{},sort:[],savedStrategies:[],watchlists:DEFAULT_WATCHLISTS,activeWatchlist:'Core',compare:[]};
const PRESETS=[
  ['VALUE','Value','Sector-relative valuation','pe > 0 and pe < sector_pe_median and pb > 0 and pb < sector_pb_median'],
  ['QUALITY','Quality','ROE/ROIC overlay','roe > sector_roe_median and roic > 0'],
  ['GROWTH','Growth','Positive revenue and profit growth','revenue_growth_yoy > 0 and net_income_growth_yoy > 0'],
  ['DIVIDEND','Dividend','Positive dividend yield','dividend_yield > 0'],
  ['MOMENTUM','Momentum','Trend + ROC','close > sma20 and sma20 > sma50 and roc20 > 0'],
  ['OVERSOLD','Oversold','RSI14 below 35','rsi14 < 35'],
  ['TREND','Trend','Price and moving-average trend','close > sma20 and sma20 > sma50'],
  ['LOW_DEBT','Low Debt','Net debt / EBITDA below 2','net_debt_ebitda >= 0 and net_debt_ebitda < 2'],
  ['HIGH_ROIC','High ROIC','ROIC above 15%','roic > 0.15'],
  ['HIGH_FCF_YIELD','High FCF Yield','FCF yield above 5%','fcf_yield > 0.05'],
  ['VALUE_QUALITY','Value + Quality','Value plus sector-relative ROE','pe > 0 and pe < sector_pe_median and roe > sector_roe_median'],
  ['VALUE_RSI','Value + RSI','Value with RSI below 45','pe > 0 and pe < sector_pe_median and rsi14 < 45'],
  ['GROWTH_MOMENTUM','Growth + Momentum','EBITDA growth plus trend','ebitda_growth_yoy > 0 and close > sma20 and roc20 > 0'],
  ['OZKAN_FILIZ_SECTOR_VALUE','Özkan Filiz Sector Value','Public methodology reconstruction','pe > 0 and pe < sector_pe_median and pb > 0 and pb < sector_pb_median and ev_ebitda > 0 and ev_ebitda < sector_ev_ebitda_median'],
  ['VOLKAN_KOCABAS_VALUE_GROWTH','Volkan Kocabaş Value Growth','Public examples reconstruction','pe > 0 and pe < sector_pe_median and pb > 0 and pb < sector_pb_median and ev_ebitda > 0 and ev_ebitda < sector_ev_ebitda_median and ebitda_growth_yoy > 0 and roe > 0'],
  ['VK_RSI_DIP_RECOVERY','Volkan Kocabaş RSI Dip','Approximation; exact public formula not verified','rsi_recent_low < 35 and rsi14 > rsi14_prev and volume > volume_ma20 and close > sma10'],
  ['VK_TREND_MOMENTUM','VK Trend Momentum','Configurable public-pattern approximation','sma20 > sma50 and close > sma20 and roc20 > 0 and volume_ratio > 1']
];
const RULE_FIELDS=['sector','pe','pb','ev_ebitda','roe','roic','net_debt_ebitda','revenue_growth_yoy','ebitda_growth_yoy','rsi14','volume_ratio','market_cap','target_upside','sector_pe_median','sector_pb_median','sector_ev_ebitda_median','sector_roe_median'];
const $=id=>document.getElementById(id);
const theme=$('theme'),density=$('density'),customAccent=$('customAccent'),verifiedOnly=$('verifiedOnly'),search=$('search'),stockTable=$('stockTable'),stockDetail=$('stockDetail'),watchlistSelect=$('watchlistSelect'),watchlistBody=$('watchlistBody'),compareBody=$('compareBody'),formulaInput=$('formulaInput'),strategyStatus=$('strategyStatus'),strategyResults=$('strategyResults'),presetCards=$('presetCards'),savedStrategies=$('savedStrategies'),ruleBuilder=$('ruleBuilder'),sourceTable=$('sourceTable'),columnPanel=$('columnPanel'),widgetSettings=$('widgetSettings'),tabSettings=$('tabSettings'),asof=$('asof'),banner=$('banner'),settingsBtn=$('settingsBtn'),closeSettings=$('closeSettings'),accent=$('accent'),columnsBtn=$('columnsBtn'),resetSettings=$('resetSettings'),formulaRun=$('formulaRun'),formulaSave=$('formulaSave'),restorePresets=$('restorePresets'),addRule=$('addRule'),buildRules=$('buildRules'),addWatchlist=$('addWatchlist'),clearCompare=$('clearCompare'),addTab=$('addTab'),newTabName=$('newTabName'),exportBtn=$('exportBtn'),importInput=$('importInput');
let data={stocks:[],sources:[],summary:{}},settings=loadSettings(),ruleRows=[{field:'pe',op:'<',value:'sector_pe_median',connector:'and',not:false},{field:'roe',op:'>',value:'sector_roe_median',connector:'and',not:false}],activeStrategy=null;
function safeRead(k){try{return localStorage.getItem(k)}catch{return null}} function safeWrite(k,v){try{localStorage.setItem(k,v);return true}catch{return false}}
function deepDefaults(parsed={}){return {...structuredClone(DEFAULTS),...parsed,widgetSizes:{...DEFAULTS.widgetSizes,...(parsed.widgetSizes||{})},columnWidths:{...(parsed.columnWidths||{})},watchlists:{...structuredClone(DEFAULT_WATCHLISTS),...(parsed.watchlists||{})},compare:Array.isArray(parsed.compare)?parsed.compare:[]}}
function loadSettings(){let raw=safeRead('bistSettings'),p={};try{p=raw?JSON.parse(raw):{}}catch{}return deepDefaults(p)}
function persist(){safeWrite('bistSettings',JSON.stringify(settings))} function save(){persist();applySettings();renderAll()}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(v,key){if(v===null||v===undefined||Number.isNaN(v))return 'N/A';if(['target_upside','roe','roic','revenue_growth_yoy','ebitda_growth_yoy','net_income_growth_yoy','revenue_quarter_yoy','net_income_quarter_yoy','revenue_ttm_growth','net_income_ttm_growth','dividend_yield','fcf_yield','earnings_yield','pe_discount_to_sector_median','pb_discount_to_sector_median','ps_discount_to_sector_median'].includes(key))return (v*100).toFixed(1)+'%';if(key==='market_cap'&&typeof v==='number')return '₺'+new Intl.NumberFormat('tr-TR',{notation:'compact',maximumFractionDigits:2}).format(v);if(typeof v==='number')return v.toLocaleString('tr-TR',{maximumFractionDigits:2});return esc(v)}
function statusClass(s){return s==='VERIFIED_2X'||s==='ACTIVE'?'good':s==='SOURCE_CONFLICT'||s==='BLOCKED'?'bad':'warn'} function widgetClass(k){return settings.widgetSizes?.[k]||(['health','sources'].includes(k)?'wide':'normal')}
function applySettings(){document.body.classList.remove('dark','light','compact','comfortable','spacious');let t=settings.theme;if(t==='system')t=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';document.body.classList.add(t,settings.density);document.documentElement.style.setProperty('--accent',settings.accent);theme.value=settings.theme;density.value=settings.density;customAccent.value=settings.accent;verifiedOnly.checked=settings.verifiedOnly}
function labels(){let m=new Map(BUILTIN_TABS);for(const c of settings.customTabs||[])m.set(c.id,c.name);return m}
function renderTabs(){const nav=document.querySelector('#tabs'),m=labels();nav.innerHTML='';let valid=(settings.tabs||[]).filter(id=>m.has(id));if(!valid.length)valid=['dashboard'];if(!valid.includes(settings.activeTab))settings.activeTab=valid[0];valid.forEach(id=>nav.insertAdjacentHTML('beforeend',`<button data-tab="${esc(id)}" class="${id===settings.activeTab?'active':''}">${esc(m.get(id))}</button>`));document.querySelectorAll('.tab.custom').forEach(x=>x.remove());for(const c of settings.customTabs||[]){if(!document.getElementById(c.id))document.querySelector('main').insertAdjacentHTML('beforeend',`<section id="${esc(c.id)}" class="tab custom"><div class="panel"><h2>${esc(c.name)}</h2><p class="muted">Personal research workspace. Layout metadata is included in Settings export/import.</p></div></section>`)}document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===settings.activeTab));nav.querySelectorAll('button').forEach(b=>b.onclick=()=>activateTab(b.dataset.tab))}
function activateTab(id){settings.activeTab=id;persist();document.querySelectorAll('#tabs button,.tab').forEach(x=>x.classList.remove('active'));document.querySelector(`#tabs button[data-tab="${CSS.escape(id)}"]`)?.classList.add('active');document.getElementById(id)?.classList.add('active');if(id==='compare')renderCompare();if(id==='watchlists')renderWatchlists()}
function renderWidgets(){const host=document.querySelector('#widgets');host.innerHTML='';const verified=data.stocks.filter(x=>x.price_status==='VERIFIED_2X');const blocks={health:`<div class="widget ${widgetClass('health')}" draggable="true" data-widget="health"><h3>DATA HEALTH</h3><div class="kpis"><div class="kpi"><span>Tracked</span><b>${data.summary?.tracked_stocks??0}</b></div><div class="kpi"><span>Verified</span><b>${data.summary?.verified_price_count??0}</b></div><div class="kpi"><span>Capital</span><b>${data.summary?.capital_explicit_count??0}</b></div><div class="kpi"><span>P/E available</span><b>${data.summary?.pe_count??0}</b></div></div><p class="muted">VERIFIED_2X requires ≥2 independent upstream lineages.</p></div>`,rsi:`<div class="widget ${widgetClass('rsi')}" draggable="true" data-widget="rsi"><h3>RSI Scanner</h3>${verified.slice().sort((a,b)=>(a.rsi14??999)-(b.rsi14??999)).slice(0,5).map(x=>`<p><b>${x.ticker}</b> <span class="${x.rsi14<40?'good':''}">RSI ${fmt(x.rsi14)}</span></p>`).join('')||'<p class="muted">No verified rows.</p>'}</div>`,value:`<div class="widget ${widgetClass('value')}" draggable="true" data-widget="value"><h3>Value Scanner</h3>${verified.slice().filter(x=>x.pe>0).sort((a,b)=>a.pe-b.pe).slice(0,5).map(x=>`<p><b>${x.ticker}</b> P/E ${fmt(x.pe)} · P/B ${fmt(x.pb)}</p>`).join('')||'<p class="muted">No verified rows.</p>'}</div>`,presets:`<div class="widget ${widgetClass('presets')}" draggable="true" data-widget="presets"><h3>Preset Library</h3><p>Value · Quality · Growth · Dividend · Momentum · Trend</p><p>Özkan Filiz · Volkan Kocabaş</p><p class="muted">Run and explain in Strategy Lab.</p></div>`,sources:`<div class="widget ${widgetClass('sources')}" draggable="true" data-widget="sources"><h3>Source Lineage</h3>${data.sources.slice(0,12).map(s=>`<p><b>${esc(s.provider||s.provider_id)}</b> <span class="status ${statusClass(s.status)}">${esc(s.status)}</span><span class="source-lineage"> → ${esc(s.upstream||s.upstream_vendor||'unknown')}</span></p>`).join('')}</div>`};for(const k of settings.widgets)if(blocks[k])host.insertAdjacentHTML('beforeend',blocks[k]);enableDrag()}
function currentRows(){let rows=data.stocks.filter(x=>!settings.verifiedOnly||x.price_status==='VERIFIED_2X'),q=(search.value||'').toUpperCase();if(q)rows=rows.filter(x=>(x.ticker||'').includes(q));return applySort(rows)}
function applySort(rows){let sorts=settings.sort||[];if(!sorts.length)return rows;return rows.slice().sort((a,b)=>{for(const s of sorts){let av=a[s.key],bv=b[s.key];if(av==null&&bv==null)continue;if(av==null)return 1;if(bv==null)return -1;if(av===bv)continue;let cmp=av>bv?1:-1;return s.dir==='desc'?-cmp:cmp}return 0})}
function inWatch(t){return (settings.watchlists[settings.activeWatchlist]||[]).includes(t)}
function renderTable(){const rows=currentRows(),cols=settings.columns;let h='<thead><tr><th>★</th><th>Cmp</th>'+cols.map(c=>{let s=(settings.sort||[]).find(x=>x.key===c),w=settings.columnWidths?.[c];return `<th data-sort="${c}" style="${w?`width:${w}px;min-width:${w}px`:''}">${c}${s?` ${s.dir==='asc'?'▲':'▼'}`:''}<span class="resizer" data-resize="${c}"></span></th>`}).join('')+'</tr></thead><tbody>';h+=rows.map(r=>`<tr><td><button class="icon-btn" data-star="${r.ticker}" title="${esc(settings.activeWatchlist)}">${inWatch(r.ticker)?'★':'☆'}</button></td><td><input type="checkbox" data-compare="${r.ticker}" ${settings.compare.includes(r.ticker)?'checked':''}></td>`+cols.map(c=>`<td>${c==='ticker'?`<button class="ticker-btn" data-detail="${r.ticker}">${r.ticker}</button>`:c==='price_status'?`<span class="status ${statusClass(r[c])}">${fmt(r[c],c)}</span>`:fmt(r[c],c)}</td>`).join('')+'</tr>').join('')+'</tbody>';stockTable.innerHTML=h;stockTable.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=e=>{if(e.target.classList.contains('resizer'))return;updateSort(th.dataset.sort,e.shiftKey);renderTable()});stockTable.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>toggleWatch(b.dataset.star));stockTable.querySelectorAll('[data-compare]').forEach(x=>x.onchange=()=>toggleCompare(x.dataset.compare,x.checked));stockTable.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showDetail(b.dataset.detail));enableColumnResize()}
function updateSort(key,multi){let cur=(settings.sort||[]).find(x=>x.key===key),next=cur?.dir==='asc'?'desc':'asc';settings.sort=multi?[...(settings.sort||[]).filter(x=>x.key!==key),{key,dir:next}]:[{key,dir:next}];persist()}
function enableColumnResize(){document.querySelectorAll('.resizer').forEach(r=>r.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const key=r.dataset.resize,th=r.parentElement,start=e.clientX,startW=th.getBoundingClientRect().width;const move=ev=>{settings.columnWidths[key]=Math.max(70,Math.round(startW+ev.clientX-start));th.style.width=settings.columnWidths[key]+'px';th.style.minWidth=settings.columnWidths[key]+'px'};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);persist()};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)})}
function showDetail(t){const r=data.stocks.find(x=>x.ticker===t);if(!r)return;let peers=data.stocks.filter(x=>x.sector===r.sector&&x.ticker!==t);stockDetail.className='detail';stockDetail.innerHTML=`<div class="section-head"><div><h3>${r.ticker} · ${esc(r.sector||'N/A')}</h3><span class="status ${statusClass(r.price_status)}">${esc(r.price_status)}</span></div><button data-addcmp="${r.ticker}">Compare</button></div><div class="metric-grid">${['price','market_cap','pe','pb','ps','earnings_yield','roe','rsi14','valuation_basis','financial_quarters_available'].map(k=>`<div><span>${k}</span><b>${fmt(r[k],k)}</b></div>`).join('')}</div><p class="muted">Peer rows in loaded universe: ${peers.map(x=>x.ticker).join(', ')||'N/A'}. Missing values are not estimated.</p>`;stockDetail.querySelector('[data-addcmp]').onclick=()=>toggleCompare(r.ticker,true)}
function toggleWatch(t){let a=settings.watchlists[settings.activeWatchlist]||[];settings.watchlists[settings.activeWatchlist]=a.includes(t)?a.filter(x=>x!==t):[...a,t];save()}
function toggleCompare(t,on){let a=settings.compare.filter(x=>x!==t);if(on){if(a.length>=6){alert('Compare supports up to 6 stocks.');renderTable();return}a.push(t)}settings.compare=a;persist();renderCompare();renderTable()}
function renderWatchlists(){watchlistSelect.innerHTML=Object.keys(settings.watchlists).map(n=>`<option ${n===settings.activeWatchlist?'selected':''}>${esc(n)}</option>`).join('');let arr=settings.watchlists[settings.activeWatchlist]||[];watchlistBody.innerHTML=arr.length?`<div class="cards">${arr.map(t=>{let r=data.stocks.find(x=>x.ticker===t)||{ticker:t};return `<div class="card"><div class="section-head"><h3>${t}</h3><button data-rmwatch="${t}">×</button></div><p>Price ${fmt(r.price)} · RSI ${fmt(r.rsi14)} · P/E ${fmt(r.pe)}</p><span class="status ${statusClass(r.price_status)}">${esc(r.price_status||'N/A')}</span></div>`}).join('')}</div>`:'<p class="muted">Bu listede henüz hisse yok. Screener içindeki ☆ düğmesini kullan.</p>';watchlistBody.querySelectorAll('[data-rmwatch]').forEach(b=>b.onclick=()=>toggleWatch(b.dataset.rmwatch))}
function renderCompare(){let rows=settings.compare.map(t=>data.stocks.find(x=>x.ticker===t)).filter(Boolean);if(rows.length<2){compareBody.innerHTML='<p class="muted">Screener’dan en az 2, en fazla 6 hisse seç.</p>';return}let metrics=['sector','price','price_status','market_cap','pe','pb','ps','earnings_yield','roe','revenue_growth_yoy','net_income_growth_yoy','rsi14','volume_ratio','valuation_basis','financial_quarters_available'];compareBody.innerHTML=`<div class="tablewrap"><table class="compare-table"><thead><tr><th>Metric</th>${rows.map(r=>`<th>${r.ticker}</th>`).join('')}</tr></thead><tbody>${metrics.map(k=>`<tr><td>${k}</td>${rows.map(r=>`<td>${fmt(r[k],k)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function splitTop(expr,word='and'){let out=[],start=0,depth=0,q=null;for(let i=0;i<expr.length;i++){let c=expr[i];if(q){if(c===q&&expr[i-1]!=='\\')q=null;continue}if(c==='"'||c==="'"){q=c;continue}if(c==='(')depth++;else if(c===')')depth--;else if(depth===0&&expr.slice(i).match(new RegExp('^\\s+'+word+'\\s+','i'))){let m=expr.slice(i).match(new RegExp('^\\s+'+word+'\\s+','i'))[0];out.push(expr.slice(start,i).trim());i+=m.length-1;start=i+1}}out.push(expr.slice(start).trim());return out.filter(Boolean)}
function runStrategy(name,expr){activeStrategy={name,expr};formulaInput.value=expr;let candidates=data.stocks.filter(x=>!settings.verifiedOnly||x.price_status==='VERIFIED_2X'),matches=[],err=null;for(const r of candidates){try{let x=SafeFormula.explain(expr,r);if(x.matched)matches.push({row:r,explain:x})}catch(e){err=e.message;break}}strategyStatus.textContent=err?`Formula error: ${err}`:`${name}: ${matches.length}/${candidates.length} matched`;strategyStatus.className=err?'bad':'muted';strategyResults.innerHTML=err?'':matches.length?matches.map(x=>{let clauses=splitTop(expr).map(c=>{let ok=false;try{ok=SafeFormula.evaluate(c,x.row).matched}catch{}return `<li class="${ok?'good':'bad'}">${ok?'✓':'✕'} ${esc(c)}</li>`}).join('');return `<details class="match"><summary><b>${x.row.ticker}</b> · P/E ${fmt(x.row.pe)} · RSI ${fmt(x.row.rsi14)}</summary><div class="explain"><b>Bu neden çıktı?</b><ul>${clauses}</ul><div class="input-chips">${Object.entries(x.explain.inputs).map(([k,v])=>`<span>${k}=${fmt(v,k)}</span>`).join('')}</div></div></details>`}).join(''):'<p class="muted">No matches.</p>'}
function renderPresets(){presetCards.innerHTML=PRESETS.map(p=>`<div class="card"><h3>${esc(p[1])}</h3><p class="muted">${esc(p[2])}</p><code>${esc(p[3])}</code><div class="card-actions"><button data-runpreset="${p[0]}">Run</button><button data-duppreset="${p[0]}">Duplicate</button></div></div>`).join('');presetCards.querySelectorAll('[data-runpreset]').forEach(b=>{let p=PRESETS.find(x=>x[0]===b.dataset.runpreset);b.onclick=()=>runStrategy(p[1],p[3])});presetCards.querySelectorAll('[data-duppreset]').forEach(b=>b.onclick=()=>duplicatePreset(b.dataset.duppreset));savedStrategies.innerHTML=settings.savedStrategies.length?settings.savedStrategies.map((s,i)=>`<div class="saved-model"><div><b>${esc(s.name)}</b><br><code>${esc(s.expr)}</code></div><div><button data-runmodel="${i}">Run</button><button data-editmodel="${i}">Edit</button><button data-delmodel="${i}">Delete</button></div></div>`).join(''):'<p class="muted">No saved custom models.</p>';savedStrategies.querySelectorAll('[data-runmodel]').forEach(b=>b.onclick=()=>{let s=settings.savedStrategies[+b.dataset.runmodel];runStrategy(s.name,s.expr)});savedStrategies.querySelectorAll('[data-editmodel]').forEach(b=>b.onclick=()=>editStrategy(+b.dataset.editmodel));savedStrategies.querySelectorAll('[data-delmodel]').forEach(b=>b.onclick=()=>{settings.savedStrategies.splice(+b.dataset.delmodel,1);save()})}
function duplicatePreset(id){let p=PRESETS.find(x=>x[0]===id);settings.savedStrategies.push({name:p[1]+' copy',expr:p[3]});save()} function editStrategy(i){let s=settings.savedStrategies[i],name=prompt('Model name',s.name);if(name===null)return;let expr=prompt('Formula',s.expr);if(expr===null)return;try{SafeFormula.evaluate(expr,data.stocks[0]||{});settings.savedStrategies[i]={name:name.trim()||s.name,expr};save()}catch(e){alert('Unsafe/invalid formula: '+e.message)}}
function renderRuleBuilder(){ruleBuilder.innerHTML=ruleRows.map((r,i)=>`<div class="rule-row"><select data-rconn="${i}" ${i===0?'disabled':''}><option>and</option><option ${r.connector==='or'?'selected':''}>or</option></select><label class="not"><input type="checkbox" data-rnot="${i}" ${r.not?'checked':''}>NOT</label><select data-rfield="${i}">${RULE_FIELDS.map(f=>`<option ${f===r.field?'selected':''}>${f}</option>`).join('')}</select><select data-rop="${i}">${['<','<=','>','>=','==','!='].map(o=>`<option ${o===r.op?'selected':''}>${esc(o)}</option>`).join('')}</select><input data-rvalue="${i}" value="${esc(r.value)}" placeholder="value or field"><button data-rdel="${i}">×</button></div>`).join('');ruleBuilder.querySelectorAll('[data-rfield]').forEach(x=>x.onchange=()=>ruleRows[+x.dataset.rfield].field=x.value);ruleBuilder.querySelectorAll('[data-rop]').forEach(x=>x.onchange=()=>ruleRows[+x.dataset.rop].op=x.value);ruleBuilder.querySelectorAll('[data-rvalue]').forEach(x=>x.oninput=()=>ruleRows[+x.dataset.rvalue].value=x.value);ruleBuilder.querySelectorAll('[data-rconn]').forEach(x=>x.onchange=()=>ruleRows[+x.dataset.rconn].connector=x.value);ruleBuilder.querySelectorAll('[data-rnot]').forEach(x=>x.onchange=()=>ruleRows[+x.dataset.rnot].not=x.checked);ruleBuilder.querySelectorAll('[data-rdel]').forEach(x=>x.onclick=()=>{ruleRows.splice(+x.dataset.rdel,1);renderRuleBuilder()})}
function quoteRuleValue(v){v=v.trim();if(v==='' )return 'null';if(RULE_FIELDS.includes(v)||/^-?\d+(\.\d+)?$/.test(v)||['true','false','null'].includes(v.toLowerCase()))return v;return JSON.stringify(v)}
function buildRuleFormula(){let expr=ruleRows.map((r,i)=>`${i?`${r.connector} `:''}${r.not?'not ':''}${r.field} ${r.op} ${quoteRuleValue(r.value)}`).join(' ');formulaInput.value=expr;return expr}
function renderSources(){const cols=['provider','status','last_success','last_failure','latency_ms','latest_data_date','freshness','fields','upstream'];sourceTable.innerHTML='<thead><tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr></thead><tbody>'+data.sources.map(r=>'<tr>'+cols.map(c=>{let v=r[c]??r[c+'_vendor']??'N/A';if(Array.isArray(v))v=v.join(', ');return `<td>${c==='status'?`<span class="status ${statusClass(v)}">${esc(v)}</span>`:esc(v)}</td>`}).join('')+'</tr>').join('')+'</tbody>'}
function renderColumnPanel(){columnPanel.innerHTML=ALL_COLUMNS.map(c=>`<div class="col-row"><label><input type="checkbox" data-col="${c}" ${settings.columns.includes(c)?'checked':''}> ${c}</label><span><button data-colmove="${c}" data-dir="-1">↑</button><button data-colmove="${c}" data-dir="1">↓</button></span></div>`).join('');columnPanel.querySelectorAll('[data-col]').forEach(x=>x.onchange=()=>{settings.columns=x.checked?[...settings.columns,x.dataset.col]:settings.columns.filter(c=>c!==x.dataset.col);save()});columnPanel.querySelectorAll('[data-colmove]').forEach(x=>x.onclick=()=>{let a=settings.columns.indexOf(x.dataset.colmove),b=a+Number(x.dataset.dir);if(a>=0&&b>=0&&b<settings.columns.length){[settings.columns[a],settings.columns[b]]=[settings.columns[b],settings.columns[a]];save()}})}
function renderWidgetSettings(){const all=['health','rsi','value','presets','sources'];widgetSettings.innerHTML=all.map(k=>`<div class="widget-setting"><label><input type="checkbox" data-widget-opt="${k}" ${settings.widgets.includes(k)?'checked':''}> ${k}</label><select data-widget-size="${k}"><option value="normal">Normal</option><option value="wide" ${widgetClass(k)==='wide'?'selected':''}>Wide</option><option value="full" ${widgetClass(k)==='full'?'selected':''}>Full</option></select></div>`).join('');widgetSettings.querySelectorAll('[data-widget-opt]').forEach(x=>x.onchange=()=>{settings.widgets=x.checked?[...settings.widgets,x.dataset.widgetOpt]:settings.widgets.filter(k=>k!==x.dataset.widgetOpt);save()});widgetSettings.querySelectorAll('[data-widget-size]').forEach(x=>x.onchange=()=>{settings.widgetSizes[x.dataset.widgetSize]=x.value;save()})}
function renderTabSettings(){let m=labels(),all=[...BUILTIN_TABS.map(x=>x[0]),...(settings.customTabs||[]).map(x=>x.id)];tabSettings.innerHTML=all.map(id=>`<div class="col-row"><label><input type="checkbox" data-tab-opt="${id}" ${(settings.tabs||[]).includes(id)?'checked':''}> ${esc(m.get(id))}</label><span><button data-tab-move="${id}" data-dir="-1">↑</button><button data-tab-move="${id}" data-dir="1">↓</button>${id.startsWith('custom-')?`<button data-tab-del="${id}">×</button>`:''}</span></div>`).join('');tabSettings.querySelectorAll('[data-tab-opt]').forEach(x=>x.onchange=()=>{settings.tabs=x.checked?[...settings.tabs,x.dataset.tabOpt]:settings.tabs.filter(k=>k!==x.dataset.tabOpt);save()});tabSettings.querySelectorAll('[data-tab-move]').forEach(x=>x.onclick=()=>{let a=settings.tabs.indexOf(x.dataset.tabMove),b=a+Number(x.dataset.dir);if(a>=0&&b>=0&&b<settings.tabs.length){[settings.tabs[a],settings.tabs[b]]=[settings.tabs[b],settings.tabs[a]];save()}});tabSettings.querySelectorAll('[data-tab-del]').forEach(x=>x.onclick=()=>{settings.customTabs=settings.customTabs.filter(c=>c.id!==x.dataset.tabDel);settings.tabs=settings.tabs.filter(k=>k!==x.dataset.tabDel);if(settings.activeTab===x.dataset.tabDel)settings.activeTab='dashboard';save()})}
function enableDrag(){let drag=null;document.querySelectorAll('[data-widget]').forEach(el=>{el.ondragstart=()=>drag=el.dataset.widget;el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();let target=el.dataset.widget;if(!drag||drag===target)return;let a=settings.widgets.indexOf(drag),b=settings.widgets.indexOf(target);settings.widgets.splice(a,1);settings.widgets.splice(b,0,drag);save()}})}
function renderAll(){renderTabs();renderWidgets();renderTable();renderSources();renderPresets();renderRuleBuilder();renderColumnPanel();renderWidgetSettings();renderTabSettings();renderWatchlists();renderCompare()}
async function boot(){data=await fetch('data/latest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()});asof.textContent=`Data as of — Prices: ${data.data_as_of?.prices??'N/A'} | Financials: ${data.data_as_of?.financials??'N/A'} | Targets: ${data.data_as_of?.targets??'N/A'}`;if(data.mode?.includes('DEMO')){banner.classList.add('show');banner.textContent='DEMO FIXTURE — this screen proves terminal logic/UI; it is not claiming live market prices.'}applySettings();renderAll()}
settingsBtn.onclick=()=>document.querySelector('#settings').classList.remove('hidden');closeSettings.onclick=()=>document.querySelector('#settings').classList.add('hidden');theme.onchange=e=>{settings.theme=e.target.value;save()};density.onchange=e=>{settings.density=e.target.value;save()};accent.onchange=e=>{settings.accent=e.target.value;save()};customAccent.oninput=e=>{settings.accent=e.target.value;save()};verifiedOnly.onchange=e=>{settings.verifiedOnly=e.target.checked;save()};search.oninput=renderTable;columnsBtn.onclick=()=>columnPanel.classList.toggle('hidden');resetSettings.onclick=()=>{settings=structuredClone(DEFAULTS);save()};formulaRun.onclick=()=>runStrategy('Custom Formula',formulaInput.value.trim());formulaSave.onclick=()=>{let expr=formulaInput.value.trim();if(!expr)return;try{SafeFormula.evaluate(expr,data.stocks[0]||{});settings.savedStrategies.push({name:'Custom '+(settings.savedStrategies.length+1),expr});save()}catch(e){alert('Unsafe/invalid formula: '+e.message)}};restorePresets.onclick=()=>{settings.savedStrategies=[];save()};addRule.onclick=()=>{ruleRows.push({field:'rsi14',op:'<',value:'45',connector:'and',not:false});renderRuleBuilder()};buildRules.onclick=()=>{let e=buildRuleFormula();runStrategy('Rule Builder',e)};watchlistSelect.onchange=e=>{settings.activeWatchlist=e.target.value;save()};addWatchlist.onclick=()=>{let n=prompt('Watchlist name');if(!n)return;n=n.trim();if(!n||settings.watchlists[n])return;settings.watchlists[n]=[];settings.activeWatchlist=n;save()};clearCompare.onclick=()=>{settings.compare=[];save()};addTab.onclick=()=>{let name=newTabName.value.trim();if(!name)return;let id='custom-'+Date.now();settings.customTabs.push({id,name});settings.tabs.push(id);newTabName.value='';save()};exportBtn.onclick=()=>{let blob=new Blob([JSON.stringify(settings,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='my-bist-layout.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};importInput.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{settings=deepDefaults(JSON.parse(r.result));save()}catch{alert('Invalid settings JSON')}};r.readAsText(f)};
boot().catch(e=>{banner.classList.add('show');banner.textContent='Data load failed: '+e.message});
